//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.1433
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcellLib.EntityListWindow {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResEntList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResEntList() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EcellLib.EntityListWindow.MessageResEntList", typeof(MessageResEntList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Can&apos;t delete this object. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrDelData {
            get {
                return ResourceManager.GetString("ErrDelData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t find the object in this model. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrGetData {
            get {
                return ResourceManager.GetString("ErrGetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t find the object by input search condition. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNotFind {
            get {
                return ResourceManager.GetString("ErrNotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fail to create the bitmap of this window. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrPrintData {
            get {
                return ResourceManager.GetString("ErrPrintData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fail to show property editor.\nPlease confirm the property of object.\n に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrShowPropEditor {
            get {
                return ResourceManager.GetString("ErrShowPropEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t start up the application assciated with this file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrStartupApp {
            get {
                return ResourceManager.GetString("ErrStartupApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add model に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PopAddModelText {
            get {
                return ResourceManager.GetString("PopAddModelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add process に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PopAddProcessText {
            get {
                return ResourceManager.GetString("PopAddProcessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add system に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PopAddSystemText {
            get {
                return ResourceManager.GetString("PopAddSystemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add variable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PopAddVariableText {
            get {
                return ResourceManager.GetString("PopAddVariableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create logger に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PopCreLoggerText {
            get {
                return ResourceManager.GetString("PopCreLoggerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PopDeleteText {
            get {
                return ResourceManager.GetString("PopDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete logger に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PopDelLoggerText {
            get {
                return ResourceManager.GetString("PopDelLoggerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Merge to supersystem に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PopMergeText {
            get {
                return ResourceManager.GetString("PopMergeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PopSearchText {
            get {
                return ResourceManager.GetString("PopSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sort by Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SortNameText {
            get {
                return ResourceManager.GetString("SortNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sort by Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SortTypeText {
            get {
                return ResourceManager.GetString("SortTypeText", resourceCulture);
            }
        }
    }
}
