//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.3082
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecell.IDE.Plugins.ProjectExplorer {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ecell.IDE.Plugins.ProjectExplorer.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Do you want to override the file [ {0} ]? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmOverrideFile {
            get {
                return ResourceManager.GetString("ConfirmOverrideFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This simulation set already exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrAlreadyExist {
            get {
                return ResourceManager.GetString("ErrAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This Stepper already exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrAlreadyExistStepper {
            get {
                return ResourceManager.GetString("ErrAlreadyExistStepper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot create the file {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrCreateFile {
            get {
                return ResourceManager.GetString("ErrCreateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   At least one Stepper is required in the model. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrDelStep {
            get {
                return ResourceManager.GetString("ErrDelStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nothing is input in {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNoInput {
            get {
                return ResourceManager.GetString("ErrNoInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save this project before adding new DM. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrProjectUnsaved {
            get {
                return ResourceManager.GetString("ErrProjectUnsaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save this project before DM is imported. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrProjectUnsavedImport {
            get {
                return ResourceManager.GetString("ErrProjectUnsavedImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot find any applications associated with this file type. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrStartupApp {
            get {
                return ResourceManager.GetString("ErrStartupApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Analysis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameAnalysis {
            get {
                return ResourceManager.GetString("NameAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DM Editor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameDMEditor {
            get {
                return ResourceManager.GetString("NameDMEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DMs に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameDMs {
            get {
                return ResourceManager.GetString("NameDMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log archives に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameLogArchives {
            get {
                return ResourceManager.GetString("NameLogArchives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Models に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameModel {
            get {
                return ResourceManager.GetString("NameModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameName {
            get {
                return ResourceManager.GetString("NameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Stepper に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameNewStepper {
            get {
                return ResourceManager.GetString("NameNewStepper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parameters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameParameters {
            get {
                return ResourceManager.GetString("NameParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Revisions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameRevisions {
            get {
                return ResourceManager.GetString("NameRevisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No entities are matched by the search condition. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoticeNotFind {
            get {
                return ResourceManager.GetString("NoticeNotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Merge to supersystem ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PopMergeText {
            get {
                return ResourceManager.GetString("PopMergeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Project Explorer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProjectExplorer {
            get {
                return ResourceManager.GetString("ProjectExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to save the project before closing this project? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveConfirm {
            get {
                return ResourceManager.GetString("SaveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select the DM directory. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectDMDir {
            get {
                return ResourceManager.GetString("SelectDMDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please input the name whose suffix is &quot;Process&quot; or &quot;Stepper&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarnDMName {
            get {
                return ResourceManager.GetString("WarnDMName", resourceCulture);
            }
        }
    }
}
