//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.1433
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcellLib.MainWindow {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResMain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResMain() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EcellLib.MainWindow.MessageResMain", typeof(MessageResMain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   The language setting will take effect after you restart this application. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmRestart {
            get {
                return ResourceManager.GetString("ConfirmRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are any invalid characters in {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrIDNG {
            get {
                return ResourceManager.GetString("ErrIDNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} should be larger than {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrLarger {
            get {
                return ResourceManager.GetString("ErrLarger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not load the file [ {0} ]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrLoadFile {
            get {
                return ResourceManager.GetString("ErrLoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not load the plugin {0} (location: {1}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrLoadPlugin {
            get {
                return ResourceManager.GetString("ErrLoadPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not load window settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrLoadWindowSettings {
            get {
                return ResourceManager.GetString("ErrLoadWindowSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No select. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNoSelect {
            get {
                return ResourceManager.GetString("ErrNoSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is not set. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNoSet {
            get {
                return ResourceManager.GetString("ErrNoSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not save the window settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSaveWindowSettings {
            get {
                return ResourceManager.GetString("ErrSaveWindowSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please set the working directory. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExpModelMes {
            get {
                return ResourceManager.GetString("ExpModelMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export Model に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExportModelDialog {
            get {
                return ResourceManager.GetString("ExportModelDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not find the file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create Copied Project. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuCopy {
            get {
                return ResourceManager.GetString("MenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create new project. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuCreateNewProject {
            get {
                return ResourceManager.GetString("MenuCreateNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create new revision. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuCreateNewRevision {
            get {
                return ResourceManager.GetString("MenuCreateNewRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuDelete {
            get {
                return ResourceManager.GetString("MenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paste. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuPaste {
            get {
                return ResourceManager.GetString("MenuPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compress to ZIP. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuSaveZip {
            get {
                return ResourceManager.GetString("MenuSaveZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The concurrency に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameConc {
            get {
                return ResourceManager.GetString("NameConc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The working directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameWorkDir {
            get {
                return ResourceManager.GetString("NameWorkDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProjectWizardCreate {
            get {
                return ResourceManager.GetString("ProjectWizardCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProjectWizardGoForward {
            get {
                return ResourceManager.GetString("ProjectWizardGoForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select DM. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProjectWizardSelectDM {
            get {
                return ResourceManager.GetString("ProjectWizardSelectDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select templete project. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProjectWizardSelectTemplete {
            get {
                return ResourceManager.GetString("ProjectWizardSelectTemplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to save the project before the project is closed? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveConfirm {
            get {
                return ResourceManager.GetString("SaveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select the dm directory. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectDMDir {
            get {
                return ResourceManager.GetString("SelectDMDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Web Browzer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartUpWindow {
            get {
                return ResourceManager.GetString("StartUpWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select the initial setting. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleInitialSet {
            get {
                return ResourceManager.GetString("TitleInitialSet", resourceCulture);
            }
        }
    }
}
