//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.3082
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecell.IDE.MainWindow {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ecell.IDE.MainWindow.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   The analysis is running. Do you really want to close this application? {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmAnalysisStop {
            get {
                return ResourceManager.GetString("ConfirmAnalysisStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The simulation is running. Do you really want to close this application?  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmClose {
            get {
                return ResourceManager.GetString("ConfirmClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to overwrite? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmOverwrite {
            get {
                return ResourceManager.GetString("ConfirmOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The language setting will be applied after you restart this application. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmRestart {
            get {
                return ResourceManager.GetString("ConfirmRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The following windows are not saved in the Window setting. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmUnsavableWindows {
            get {
                return ResourceManager.GetString("ConfirmUnsavableWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your changes have not been saved. Are you sure to exit? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmUnsaved {
            get {
                return ResourceManager.GetString("ConfirmUnsaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save as new Project. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTitleSaveAs {
            get {
                return ResourceManager.GetString("DialogTitleSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Closing dockable pane {0}... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockClosing {
            get {
                return ResourceManager.GetString("DockClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preparing dockable pane {0}... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DockPreparing {
            get {
                return ResourceManager.GetString("DockPreparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The project &quot;{0}&quot; already exists.  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrExistProject {
            get {
                return ResourceManager.GetString("ErrExistProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to parse {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrFailedToParse {
            get {
                return ResourceManager.GetString("ErrFailedToParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} contains some invalid chacters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrIDNG {
            get {
                return ResourceManager.GetString("ErrIDNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value[ {0} ] is not valid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrInvalidValue {
            get {
                return ResourceManager.GetString("ErrInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} should be greater than {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrLarger {
            get {
                return ResourceManager.GetString("ErrLarger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot load the file [ {0} ]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrLoadFile {
            get {
                return ResourceManager.GetString("ErrLoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not load the project while simulation is running. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrLoadWhileSimulation {
            get {
                return ResourceManager.GetString("ErrLoadWhileSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot load the window settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrLoadWindowSettings {
            get {
                return ResourceManager.GetString("ErrLoadWindowSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nothing selected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNoSelect {
            get {
                return ResourceManager.GetString("ErrNoSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is not set. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNoSet {
            get {
                return ResourceManager.GetString("ErrNoSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save this project before the analysis is saved. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrProjectUnsaved {
            get {
                return ResourceManager.GetString("ErrProjectUnsaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot save the window settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSaveWindowSettings {
            get {
                return ResourceManager.GetString("ErrSaveWindowSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Authorization exception for the workspace [ {0} ]. Please confirm your access right to the workspace. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrUnauthorizedAccess {
            get {
                return ResourceManager.GetString("ErrUnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please set the project root folder. Project is saved in this folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExpModelMes {
            get {
                return ResourceManager.GetString("ExpModelMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export model に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExportModelDialog {
            get {
                return ResourceManager.GetString("ExportModelDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   usermanual.pdf に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileManual {
            get {
                return ResourceManager.GetString("FileManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot find the specified file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create a copy of this projct に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuCopy {
            get {
                return ResourceManager.GetString("MenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create new project に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuCreateNewProject {
            get {
                return ResourceManager.GetString("MenuCreateNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create new revision に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuCreateNewRevision {
            get {
                return ResourceManager.GetString("MenuCreateNewRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuDelete {
            get {
                return ResourceManager.GetString("MenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manual for Docking Window. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuDockManual {
            get {
                return ResourceManager.GetString("MenuDockManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manual に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuManual {
            get {
                return ResourceManager.GetString("MenuManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paste に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuPaste {
            get {
                return ResourceManager.GetString("MenuPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recenty used projects. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuRecentProjects {
            get {
                return ResourceManager.GetString("MenuRecentProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compress to Zip に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuSaveZip {
            get {
                return ResourceManager.GetString("MenuSaveZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tutorial に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuTutorial {
            get {
                return ResourceManager.GetString("MenuTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connectiing... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageWebBrowse {
            get {
                return ResourceManager.GetString("MessageWebBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The concurrency に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameConc {
            get {
                return ResourceManager.GetString("NameConc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameGeneral {
            get {
                return ResourceManager.GetString("NameGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Job manage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameJobManage {
            get {
                return ResourceManager.GetString("NameJobManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameLanguageSetting {
            get {
                return ResourceManager.GetString("NameLanguageSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Model に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameModel {
            get {
                return ResourceManager.GetString("NameModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Script Editor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameScriptEditor {
            get {
                return ResourceManager.GetString("NameScriptEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Simulation parameter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameSimParam {
            get {
                return ResourceManager.GetString("NameSimParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Simulation result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameSimResult {
            get {
                return ResourceManager.GetString("NameSimResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameStatusError {
            get {
                return ResourceManager.GetString("NameStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Finished に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameStatusFinished {
            get {
                return ResourceManager.GetString("NameStatusFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameStatusNone {
            get {
                return ResourceManager.GetString("NameStatusNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Queued に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameStatusQueue {
            get {
                return ResourceManager.GetString("NameStatusQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Running に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameStatusRunning {
            get {
                return ResourceManager.GetString("NameStatusRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stopped に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameStatusStopped {
            get {
                return ResourceManager.GetString("NameStatusStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The project root folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameWorkDir {
            get {
                return ResourceManager.GetString("NameWorkDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProjectWizardCreate {
            get {
                return ResourceManager.GetString("ProjectWizardCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProjectWizardGoForward {
            get {
                return ResourceManager.GetString("ProjectWizardGoForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select a templete for the new project. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProjectWizardSelectTemplete {
            get {
                return ResourceManager.GetString("ProjectWizardSelectTemplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input project settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProjectWizardSetting {
            get {
                return ResourceManager.GetString("ProjectWizardSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to save the project before closing this project? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveConfirm {
            get {
                return ResourceManager.GetString("SaveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select the DM directory. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectDMDir {
            get {
                return ResourceManager.GetString("SelectDMDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Web Browser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartUpWindow {
            get {
                return ResourceManager.GetString("StartUpWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select the initial setting. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleInitialSet {
            get {
                return ResourceManager.GetString("TitleInitialSet", resourceCulture);
            }
        }
    }
}
