//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.832
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecell.IDE.Plugins.PathwayWindow {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ecell.IDE.Plugins.PathwayWindow.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Create alias に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuAlias {
            get {
                return ResourceManager.GetString("CanvasMenuAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set opposite direction に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuAnotherArrow {
            get {
                return ResourceManager.GetString("CanvasMenuAnotherArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set both directions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuBidirArrow {
            get {
                return ResourceManager.GetString("CanvasMenuBidirArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Layer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuChangeLayer {
            get {
                return ResourceManager.GetString("CanvasMenuChangeLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set effector に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuConstantLine {
            get {
                return ResourceManager.GetString("CanvasMenuConstantLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Copy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuCopy {
            get {
                return ResourceManager.GetString("CanvasMenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create logger に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuCreateLogger {
            get {
                return ResourceManager.GetString("CanvasMenuCreateLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cu&amp;t に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuCut {
            get {
                return ResourceManager.GetString("CanvasMenuCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuDelete {
            get {
                return ResourceManager.GetString("CanvasMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete logger に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuDeleteLogger {
            get {
                return ResourceManager.GetString("CanvasMenuDeleteLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Layout に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuLayout {
            get {
                return ResourceManager.GetString("CanvasMenuLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Merge to supersystem に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuMerge {
            get {
                return ResourceManager.GetString("CanvasMenuMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Paste に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuPaste {
            get {
                return ResourceManager.GetString("CanvasMenuPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure merge the component in system to upper system. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmMerge {
            get {
                return ResourceManager.GetString("ConfirmMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Animation setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTextAnimationSetting {
            get {
                return ResourceManager.GetString("DialogTextAnimationSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Background color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTextBackgroundBrush {
            get {
                return ResourceManager.GetString("DialogTextBackgroundBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Center color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTextCenterBrush {
            get {
                return ResourceManager.GetString("DialogTextCenterBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shape settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTextComponentSetting {
            get {
                return ResourceManager.GetString("DialogTextComponentSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edge color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTextEdgeBrush {
            get {
                return ResourceManager.GetString("DialogTextEdgeBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edge width に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTextEdgeWidth {
            get {
                return ResourceManager.GetString("DialogTextEdgeWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTextEditMode {
            get {
                return ResourceManager.GetString("DialogTextEditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Object shape に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTextFigure {
            get {
                return ResourceManager.GetString("DialogTextFigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fill color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTextFillBrush {
            get {
                return ResourceManager.GetString("DialogTextFillBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Icon file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTextIconFile {
            get {
                return ResourceManager.GetString("DialogTextIconFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gradation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTextIsGradation {
            get {
                return ResourceManager.GetString("DialogTextIsGradation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Line color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTextLineBrush {
            get {
                return ResourceManager.GetString("DialogTextLineBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logarithmic scale に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTextLogarithmic {
            get {
                return ResourceManager.GetString("DialogTextLogarithmic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max edge width に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTextMaxEdgeWidth {
            get {
                return ResourceManager.GetString("DialogTextMaxEdgeWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NG color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTextNGBrush {
            get {
                return ResourceManager.GetString("DialogTextNGBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Normal edge に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTextNormalEdge {
            get {
                return ResourceManager.GetString("DialogTextNormalEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pathway settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTextPathwaySetting {
            get {
                return ResourceManager.GetString("DialogTextPathwaySetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Property color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTextPropertyBrush {
            get {
                return ResourceManager.GetString("DialogTextPropertyBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTextTextBrush {
            get {
                return ResourceManager.GetString("DialogTextTextBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upper threshold に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTextThresholdHigh {
            get {
                return ResourceManager.GetString("DialogTextThresholdHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lower threshold に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTextThresholdLow {
            get {
                return ResourceManager.GetString("DialogTextThresholdLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTextViewMode {
            get {
                return ResourceManager.GetString("DialogTextViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Entity {0} has already existed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrAlrExist {
            get {
                return ResourceManager.GetString("ErrAlrExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The setting file for shape of entities is imcomplete. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrCompInvalid {
            get {
                return ResourceManager.GetString("ErrCompInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot create the shape of entities. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrCreateComponent {
            get {
                return ResourceManager.GetString("ErrCreateComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Autolayout process of this algorithm was failed due to an unexpected error. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrLayout {
            get {
                return ResourceManager.GetString("ErrLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading pathway layouts were failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrLoadLEML {
            get {
                return ResourceManager.GetString("ErrLoadLEML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot load window settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrLoadWindowSettings {
            get {
                return ResourceManager.GetString("ErrLoadWindowSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot put any objects to outside root System. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrOutRoot {
            get {
                return ResourceManager.GetString("ErrOutRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot partially-overlap with other Systems. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrOverSystem {
            get {
                return ResourceManager.GetString("ErrOverSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saving pathway layouts were failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSaveLEML {
            get {
                return ResourceManager.GetString("ErrSaveLEML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The pointed place has no space to paste the System. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSystemOverlap {
            get {
                return ResourceManager.GetString("ErrSystemOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The type of  added Entity is unknown. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrUnknowType {
            get {
                return ResourceManager.GetString("ErrUnknowType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input new layer name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayerDialogMessage {
            get {
                return ResourceManager.GetString("LayerDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Layer name input dialog に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayerDialogTitle {
            get {
                return ResourceManager.GetString("LayerDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change layer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayerMenuChange {
            get {
                return ResourceManager.GetString("LayerMenuChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New layer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayerMenuCreate {
            get {
                return ResourceManager.GetString("LayerMenuCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete layer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayerMenuDelete {
            get {
                return ResourceManager.GetString("LayerMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Merge layer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayerMenuMerge {
            get {
                return ResourceManager.GetString("LayerMenuMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move to back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayerMenuMoveBack {
            get {
                return ResourceManager.GetString("LayerMenuMoveBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move to front に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayerMenuMoveFront {
            get {
                return ResourceManager.GetString("LayerMenuMoveFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename layer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayerMenuRename {
            get {
                return ResourceManager.GetString("LayerMenuRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select nodes under... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayerMenuSelectNodes {
            get {
                return ResourceManager.GetString("LayerMenuSelectNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemEdit {
            get {
                return ResourceManager.GetString("MenuItemEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export diagrams に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemExport {
            get {
                return ResourceManager.GetString("MenuItemExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export Image... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemExportImage {
            get {
                return ResourceManager.GetString("MenuItemExportImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export SVG format... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemExportSVG {
            get {
                return ResourceManager.GetString("MenuItemExportSVG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemFile {
            get {
                return ResourceManager.GetString("MenuItemFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Focus the selected object, に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemFocus {
            get {
                return ResourceManager.GetString("MenuItemFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Layout に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemLayout {
            get {
                return ResourceManager.GetString("MenuItemLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pathway settings... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemSetup {
            get {
                return ResourceManager.GetString("MenuItemSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show &amp;IDs(Pathway) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemShowID {
            get {
                return ResourceManager.GetString("MenuItemShowID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;View に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemView {
            get {
                return ResourceManager.GetString("MenuItemView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemViewMode {
            get {
                return ResourceManager.GetString("MenuItemViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export diagrams. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuToolTipExport {
            get {
                return ResourceManager.GetString("MenuToolTipExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export image file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuToolTipExportImage {
            get {
                return ResourceManager.GetString("MenuToolTipExportImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export SVG format. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuToolTipExportSVG {
            get {
                return ResourceManager.GetString("MenuToolTipExportSVG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Focus the selected object. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuToolTipFocus {
            get {
                return ResourceManager.GetString("MenuToolTipFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show property dialog of PathwayWindow. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuToolTipSetup {
            get {
                return ResourceManager.GetString("MenuToolTipSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change the visibility mode of each object ID. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuToolTipShowID {
            get {
                return ResourceManager.GetString("MenuToolTipShowID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change view mode of canvas. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuToolTipViewMode {
            get {
                return ResourceManager.GetString("MenuToolTipViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Now layouting ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageLayout {
            get {
                return ResourceManager.GetString("MessageLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Now loading model ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageLoadModel {
            get {
                return ResourceManager.GetString("MessageLoadModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create effectors. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolButtonAddConstant {
            get {
                return ResourceManager.GetString("ToolButtonAddConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create reversible reactions. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolButtonAddMutualReaction {
            get {
                return ResourceManager.GetString("ToolButtonAddMutualReaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create irreversible reactions. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolButtonAddOnewayReaction {
            get {
                return ResourceManager.GetString("ToolButtonAddOnewayReaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create new Process. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolButtonCreateProcess {
            get {
                return ResourceManager.GetString("ToolButtonCreateProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create new System. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolButtonCreateSystem {
            get {
                return ResourceManager.GetString("ToolButtonCreateSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create new text box. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolButtonCreateText {
            get {
                return ResourceManager.GetString("ToolButtonCreateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create new Variable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolButtonCreateVariable {
            get {
                return ResourceManager.GetString("ToolButtonCreateVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drag canvas. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolButtonMoveCanvas {
            get {
                return ResourceManager.GetString("ToolButtonMoveCanvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Object select. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolButtonSelectMode {
            get {
                return ResourceManager.GetString("ToolButtonSelectMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom in に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolButtonZoomIn {
            get {
                return ResourceManager.GetString("ToolButtonZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom out に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolButtonZoomOut {
            get {
                return ResourceManager.GetString("ToolButtonZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Layer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowLayer {
            get {
                return ResourceManager.GetString("WindowLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Overview に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowOverview {
            get {
                return ResourceManager.GetString("WindowOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Network に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowPathway {
            get {
                return ResourceManager.GetString("WindowPathway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stencil に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowStencil {
            get {
                return ResourceManager.GetString("WindowStencil", resourceCulture);
            }
        }
    }
}
