//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.832
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcellLib.PathwayWindow {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResPathway {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResPathway() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EcellLib.PathwayWindow.MessageResPathway", typeof(MessageResPathway).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CopyMenuText {
            get {
                return ResourceManager.GetString("CopyMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure merge the component in system to upper system. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmMerge {
            get {
                return ResourceManager.GetString("ConfirmMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create Logger に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateLogMenuText {
            get {
                return ResourceManager.GetString("CreateLogMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Logger に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeleteLogMenuText {
            get {
                return ResourceManager.GetString("DeleteLogMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeleteMenuText {
            get {
                return ResourceManager.GetString("DeleteMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not add the object. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrAddObj {
            get {
                return ResourceManager.GetString("ErrAddObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not find the added object. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrAddObjNot {
            get {
                return ResourceManager.GetString("ErrAddObjNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Already connected ! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrAlrConnect {
            get {
                return ResourceManager.GetString("ErrAlrConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///    has already existed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrAlrExist {
            get {
                return ResourceManager.GetString("ErrAlrExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ComponentSettings.xml is imcomplete for the following reason に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrCompInvalid {
            get {
                return ResourceManager.GetString("ErrCompInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default process was not found in the ComponentSettings.xml file, so hard coded one will be used instead.\n\n に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrComProcess {
            get {
                return ResourceManager.GetString("ErrComProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default system was not found in the ComponentSettings.xml file, so hard coded one will be used instead.\n\n に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrComSystem {
            get {
                return ResourceManager.GetString("ErrComSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default variable was not found in the ComponentSettings.xml file, so hard coded one will be used instead.\n\n に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrComVariable {
            get {
                return ResourceManager.GetString("ErrComVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fail to convert the information to component object. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrCreateKind {
            get {
                return ResourceManager.GetString("ErrCreateKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not delete the root system. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrDelRoot {
            get {
                return ResourceManager.GetString("ErrDelRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No set the object id. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrKeyNot {
            get {
                return ResourceManager.GetString("ErrKeyNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t execute this layout due to an unexpected error, sorry. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrLayout {
            get {
                return ResourceManager.GetString("ErrLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t find ComponentSettings.xml file in the &lt;ECell-HOME&gt;&quot;\\plugins\\pathway directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNotComXml {
            get {
                return ResourceManager.GetString("ErrNotComXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Canvas ID is not set for  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNotSetCanvas {
            get {
                return ResourceManager.GetString("ErrNotSetCanvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not create an object outside the root system に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrOutRoot {
            get {
                return ResourceManager.GetString("ErrOutRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A system can&apos;t be overlapping other systems に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrOverSystem {
            get {
                return ResourceManager.GetString("ErrOverSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are the objects that have the same ID. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSameObj {
            get {
                return ResourceManager.GetString("ErrSameObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The added object have the unknown type. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrUnknowType {
            get {
                return ResourceManager.GetString("ErrUnknowType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show &amp;IDs(Pathway) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemShowIDText {
            get {
                return ResourceManager.GetString("MenuItemShowIDText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Merge to supersystem に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MergeMenuText {
            get {
                return ResourceManager.GetString("MergeMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select at least one node to layout に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgLayoutNoNode {
            get {
                return ResourceManager.GetString("MsgLayoutNoNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paste に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PasteMenuText {
            get {
                return ResourceManager.GetString("PasteMenuText", resourceCulture);
            }
        }
    }
}
