//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.3082
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecell.IDE.Plugins.PathwayWindow {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ecell.IDE.Plugins.PathwayWindow.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Create effectors. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonToolTipAddConstant {
            get {
                return ResourceManager.GetString("ButtonToolTipAddConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create reversible reactions. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonToolTipAddMutualReaction {
            get {
                return ResourceManager.GetString("ButtonToolTipAddMutualReaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create irreversible reactions. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonToolTipAddOnewayReaction {
            get {
                return ResourceManager.GetString("ButtonToolTipAddOnewayReaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create new Process. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonToolTipCreateProcess {
            get {
                return ResourceManager.GetString("ButtonToolTipCreateProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create new System. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonToolTipCreateSystem {
            get {
                return ResourceManager.GetString("ButtonToolTipCreateSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create new text box. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonToolTipCreateText {
            get {
                return ResourceManager.GetString("ButtonToolTipCreateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create new Variable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonToolTipCreateVariable {
            get {
                return ResourceManager.GetString("ButtonToolTipCreateVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drag canvas. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonToolTipMoveCanvas {
            get {
                return ResourceManager.GetString("ButtonToolTipMoveCanvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change the visibility of Overview panel. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonToolTipOverview {
            get {
                return ResourceManager.GetString("ButtonToolTipOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select entity. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonToolTipSelectMode {
            get {
                return ResourceManager.GetString("ButtonToolTipSelectMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom in に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonToolTipZoomIn {
            get {
                return ResourceManager.GetString("ButtonToolTipZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom out に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonToolTipZoomOut {
            get {
                return ResourceManager.GetString("ButtonToolTipZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create alias に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuAlias {
            get {
                return ResourceManager.GetString("CanvasMenuAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Center に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuAlignCenter {
            get {
                return ResourceManager.GetString("CanvasMenuAlignCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuAlignLeft {
            get {
                return ResourceManager.GetString("CanvasMenuAlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuAlignRight {
            get {
                return ResourceManager.GetString("CanvasMenuAlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set opposite direction に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuAnotherArrow {
            get {
                return ResourceManager.GetString("CanvasMenuAnotherArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set both directions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuBidirArrow {
            get {
                return ResourceManager.GetString("CanvasMenuBidirArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Layer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuChangeLayer {
            get {
                return ResourceManager.GetString("CanvasMenuChangeLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set effector に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuConstantLine {
            get {
                return ResourceManager.GetString("CanvasMenuConstantLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Copy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuCopy {
            get {
                return ResourceManager.GetString("CanvasMenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mark the property as logging に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuCreateLogger {
            get {
                return ResourceManager.GetString("CanvasMenuCreateLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cu&amp;t に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuCut {
            get {
                return ResourceManager.GetString("CanvasMenuCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuDelete {
            get {
                return ResourceManager.GetString("CanvasMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete logger に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuDeleteLogger {
            get {
                return ResourceManager.GetString("CanvasMenuDeleteLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Layout に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuLayout {
            get {
                return ResourceManager.GetString("CanvasMenuLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set oneway direction に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuOnewayArrow {
            get {
                return ResourceManager.GetString("CanvasMenuOnewayArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Paste に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuPaste {
            get {
                return ResourceManager.GetString("CanvasMenuPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alignment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuTextAlign {
            get {
                return ResourceManager.GetString("CanvasMenuTextAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset Diagram settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTextConfirmReset {
            get {
                return ResourceManager.GetString("DialogTextConfirmReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automatic setting of the threshold of Edge width. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTooltipAutoThreshold {
            get {
                return ResourceManager.GetString("DialogTooltipAutoThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Entity {0} already exists. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrAlrExist {
            get {
                return ResourceManager.GetString("ErrAlrExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The setting file for shapes of entities is incorrect. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrCompInvalid {
            get {
                return ResourceManager.GetString("ErrCompInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to create movie file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrCreateAvi {
            get {
                return ResourceManager.GetString("ErrCreateAvi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot create the shape of entities. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrCreateComponent {
            get {
                return ResourceManager.GetString("ErrCreateComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to create edge. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrCreateEdge {
            get {
                return ResourceManager.GetString("ErrCreateEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value[ {0} ] is not valid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrInvalidValue {
            get {
                return ResourceManager.GetString("ErrInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Autolayout process failed with an unexpected error. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrLayout {
            get {
                return ResourceManager.GetString("ErrLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot load the layout information. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrLoadLEML {
            get {
                return ResourceManager.GetString("ErrLoadLEML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nothing is input in {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNoInput {
            get {
                return ResourceManager.GetString("ErrNoInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Entity {0} doesn&apos;t exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNotFound {
            get {
                return ResourceManager.GetString("ErrNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot put any objects to outside root System. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrOutRoot {
            get {
                return ResourceManager.GetString("ErrOutRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot partially-overlap with other Systems. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrOverSystem {
            get {
                return ResourceManager.GetString("ErrOverSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot save the layout information. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSaveLEML {
            get {
                return ResourceManager.GetString("ErrSaveLEML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The pointed place has no space to paste the System. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSystemOverlap {
            get {
                return ResourceManager.GetString("ErrSystemOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The type of added Entity is unknown. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrUnknowType {
            get {
                return ResourceManager.GetString("ErrUnknowType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not update the shape property. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrUpdateConfig {
            get {
                return ResourceManager.GetString("ErrUpdateConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayerColumnName {
            get {
                return ResourceManager.GetString("LayerColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayerColumnShow {
            get {
                return ResourceManager.GetString("LayerColumnShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please input the new layer name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayerDialogChange {
            get {
                return ResourceManager.GetString("LayerDialogChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please input the new layer name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayerDialogMessage {
            get {
                return ResourceManager.GetString("LayerDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Layer name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayerDialogTitle {
            get {
                return ResourceManager.GetString("LayerDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change layer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayerMenuChange {
            get {
                return ResourceManager.GetString("LayerMenuChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New layer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayerMenuCreate {
            get {
                return ResourceManager.GetString("LayerMenuCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayerMenuDelete {
            get {
                return ResourceManager.GetString("LayerMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Merge layer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayerMenuMerge {
            get {
                return ResourceManager.GetString("LayerMenuMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move to back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayerMenuMoveBack {
            get {
                return ResourceManager.GetString("LayerMenuMoveBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move to front に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayerMenuMoveFront {
            get {
                return ResourceManager.GetString("LayerMenuMoveFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayerMenuRename {
            get {
                return ResourceManager.GetString("LayerMenuRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select nodes on thie layer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayerMenuSelectNodes {
            get {
                return ResourceManager.GetString("LayerMenuSelectNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Animation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemAnimation {
            get {
                return ResourceManager.GetString("MenuItemAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemEdit {
            get {
                return ResourceManager.GetString("MenuItemEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export diagram image... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemExport {
            get {
                return ResourceManager.GetString("MenuItemExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemFile {
            get {
                return ResourceManager.GetString("MenuItemFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto Zoom に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemFocus {
            get {
                return ResourceManager.GetString("MenuItemFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Layout に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemLayout {
            get {
                return ResourceManager.GetString("MenuItemLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diagram settings... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemSetup {
            get {
                return ResourceManager.GetString("MenuItemSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show &amp;IDs(Pathway) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemShowID {
            get {
                return ResourceManager.GetString("MenuItemShowID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;View に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemView {
            get {
                return ResourceManager.GetString("MenuItemView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set animation of canvas. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuToolTipAnimation {
            get {
                return ResourceManager.GetString("MenuToolTipAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Focus the selected entity. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuToolTipFocus {
            get {
                return ResourceManager.GetString("MenuToolTipFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change the visibility mode of each object ID. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuToolTipShowID {
            get {
                return ResourceManager.GetString("MenuToolTipShowID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select the merged layer. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MergeLayerDialogMessage {
            get {
                return ResourceManager.GetString("MergeLayerDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Merge layer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MergeLayerDialogText {
            get {
                return ResourceManager.GetString("MergeLayerDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Now layouting ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageLayout {
            get {
                return ResourceManager.GetString("MessageLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Now loading model ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageLoadModel {
            get {
                return ResourceManager.GetString("MessageLoadModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Layer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowLayer {
            get {
                return ResourceManager.GetString("WindowLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diagram に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowPathway {
            get {
                return ResourceManager.GetString("WindowPathway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stencil に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowStencil {
            get {
                return ResourceManager.GetString("WindowStencil", resourceCulture);
            }
        }
    }
}
