//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.1433
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecell.IDE.Plugins.Analysis {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ecell.IDE.Plugins.Analysis.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Some errors occurred in the parameters. Do you want to proceed to the result? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmFindErrorJob {
            get {
                return ResourceManager.GetString("ConfirmFindErrorJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure to abort this analysis? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmStopAnalysis {
            get {
                return ResourceManager.GetString("ConfirmStopAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execution of {0} failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrExecute {
            get {
                return ResourceManager.GetString("ErrExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value is not valid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrInvalidValue {
            get {
                return ResourceManager.GetString("ErrInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} should be greater than {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrLarger {
            get {
                return ResourceManager.GetString("ErrLarger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nothing is input in {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNoInput {
            get {
                return ResourceManager.GetString("ErrNoInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The same parameter is selected for X-axis and Y-axis. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSameAxis {
            get {
                return ResourceManager.GetString("ErrSameAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot save {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSaveFile {
            get {
                return ResourceManager.GetString("ErrSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The number of {0} should be {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSetNumber {
            get {
                return ResourceManager.GetString("ErrSetNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The number of {0} should be more than {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSetNumberMore {
            get {
                return ResourceManager.GetString("ErrSetNumberMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} should be less than {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSmaller {
            get {
                return ResourceManager.GetString("ErrSmaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Executuion of {0} has finished. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InfoFinishExecute {
            get {
                return ResourceManager.GetString("InfoFinishExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Bifurcation analysis ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemBifurcationAnalysis {
            get {
                return ResourceManager.GetString("MenuItemBifurcationAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Load analysis parameters ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemLoadAnalysisCond {
            get {
                return ResourceManager.GetString("MenuItemLoadAnalysisCond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   L&amp;oad analysis results ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemLoadAnalysisResult {
            get {
                return ResourceManager.GetString("MenuItemLoadAnalysisResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Parameter estimation ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemParameterEstimation {
            get {
                return ResourceManager.GetString("MenuItemParameterEstimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Robust analysis ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemRobustAnalysis {
            get {
                return ResourceManager.GetString("MenuItemRobustAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sav&amp;e analysis parameters ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemSaveAnalysisCond {
            get {
                return ResourceManager.GetString("MenuItemSaveAnalysisCond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sav&amp;e analysis results ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemSaveAnalysisResult {
            get {
                return ResourceManager.GetString("MenuItemSaveAnalysisResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Sensitivity analysis ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemSensitivityAnalysis {
            get {
                return ResourceManager.GetString("MenuItemSensitivityAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Abort analysis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemStopAnalysis {
            get {
                return ResourceManager.GetString("MenuItemStopAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execute bifurcation analysis. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuToolTipBifurcationAnalysis {
            get {
                return ResourceManager.GetString("MenuToolTipBifurcationAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load the analysis settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuToolTipLoadAnalysisCond {
            get {
                return ResourceManager.GetString("MenuToolTipLoadAnalysisCond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load the analysis results. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuToolTipLoadAnalysisResult {
            get {
                return ResourceManager.GetString("MenuToolTipLoadAnalysisResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execute patameter estimation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuToolTipParameterEstimation {
            get {
                return ResourceManager.GetString("MenuToolTipParameterEstimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execute robust analysis. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuToolTipRobustAnalysis {
            get {
                return ResourceManager.GetString("MenuToolTipRobustAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save the analysis settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuToolTipSaveAnalysisCond {
            get {
                return ResourceManager.GetString("MenuToolTipSaveAnalysisCond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save the analysis results. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuToolTipSaveAnalysisResult {
            get {
                return ResourceManager.GetString("MenuToolTipSaveAnalysisResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execute sensitivity analysis. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuToolTipSensitivityAnalysis {
            get {
                return ResourceManager.GetString("MenuToolTipSensitivityAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Abort the analysis. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuToolTipStopAnalysis {
            get {
                return ResourceManager.GetString("MenuToolTipStopAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The absolute perturbation bounds に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameAbsolutePert {
            get {
                return ResourceManager.GetString("NameAbsolutePert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bifurcation analysis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameBifurcation {
            get {
                return ResourceManager.GetString("NameBifurcation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Evaluation function に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameEstimationForm {
            get {
                return ResourceManager.GetString("NameEstimationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The number of generations に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameGenerationNum {
            get {
                return ResourceManager.GetString("NameGenerationNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max frequency に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameMaxFrequency {
            get {
                return ResourceManager.GetString("NameMaxFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The number of samples for FFT に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameMaxSample {
            get {
                return ResourceManager.GetString("NameMaxSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Min frequency に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameMinFrequency {
            get {
                return ResourceManager.GetString("NameMinFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The observed parameter set に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameObservedData {
            get {
                return ResourceManager.GetString("NameObservedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The parameter set に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameParameterData {
            get {
                return ResourceManager.GetString("NameParameterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parameter estimation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameParameterEstimate {
            get {
                return ResourceManager.GetString("NameParameterEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The number of populations に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NamePopulation {
            get {
                return ResourceManager.GetString("NamePopulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The relative perturbation bounds に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameRelativePert {
            get {
                return ResourceManager.GetString("NameRelativePert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Robust analysis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameRobustAnalysis {
            get {
                return ResourceManager.GetString("NameRobustAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sensitivity analysis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameSensAnalysis {
            get {
                return ResourceManager.GetString("NameSensAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The simulation duration に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameSimulationTime {
            get {
                return ResourceManager.GetString("NameSimulationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The number of steps に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameStepNum {
            get {
                return ResourceManager.GetString("NameStepNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameWindowSize {
            get {
                return ResourceManager.GetString("NameWindowSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reflect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReflectMenuText {
            get {
                return ResourceManager.GetString("ReflectMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input the absolute perturbation at the defalut value. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolTipAbsolutePert {
            get {
                return ResourceManager.GetString("ToolTipAbsolutePert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input the iteration of analysis as the generation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolTipGeneration {
            get {
                return ResourceManager.GetString("ToolTipGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input the max frequency used in FFT. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolTipMaxFFT {
            get {
                return ResourceManager.GetString("ToolTipMaxFFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input the max number of data to calculate FFT. This value should be smaller than 8192. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolTipMaxInputSize {
            get {
                return ResourceManager.GetString("ToolTipMaxInputSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input the min frequency used in FFT. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolTipMinFFT {
            get {
                return ResourceManager.GetString("ToolTipMinFFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input the parameter to judge whether this system is stabile. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolTipObservedGrid {
            get {
                return ResourceManager.GetString("ToolTipObservedGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input the parameter changed the value to judge the stability of system. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolTipParameterGrid {
            get {
                return ResourceManager.GetString("ToolTipParameterGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input the population at the generation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolTipPopulation {
            get {
                return ResourceManager.GetString("ToolTipPopulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input the relative perturbation at the defalut value. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolTipRelativePert {
            get {
                return ResourceManager.GetString("ToolTipRelativePert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input the number of samples to check the stability of system. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolTipSampleNumber {
            get {
                return ResourceManager.GetString("ToolTipSampleNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input the simulation time to get the data used by judgement. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolTipSimulationTime {
            get {
                return ResourceManager.GetString("ToolTipSimulationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input the number of step to get the change of value to calculate the sensitivity. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolTipStep {
            get {
                return ResourceManager.GetString("ToolTipStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input the unknown parameter to search the optimal value. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolTipUnknownParameterGrid {
            get {
                return ResourceManager.GetString("ToolTipUnknownParameterGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input the time size of data used by judgement. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolTipWindowSize {
            get {
                return ResourceManager.GetString("ToolTipWindowSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input the estimation formulator used in the judgement. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToopTipEstimation {
            get {
                return ResourceManager.GetString("ToopTipEstimation", resourceCulture);
            }
        }
    }
}
