//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.1433
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcellLib.Analysis {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResAnalysis {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResAnalysis() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EcellLib.Analysis.MessageResAnalysis", typeof(MessageResAnalysis).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   AnalysisResults に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AnalysisResultWindow {
            get {
                return ResourceManager.GetString("AnalysisResultWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AnalysisSettings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AnalysisWindow {
            get {
                return ResourceManager.GetString("AnalysisWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to close this window? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmClose {
            get {
                return ResourceManager.GetString("ConfirmClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are any error job. Do you want to confirm the result? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmFindErrorJob {
            get {
                return ResourceManager.GetString("ConfirmFindErrorJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to stop the analysis? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmStopAnalysis {
            get {
                return ResourceManager.GetString("ConfirmStopAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to execute the {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrExecute {
            get {
                return ResourceManager.GetString("ErrExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} should be larger than {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrLarger {
            get {
                return ResourceManager.GetString("ErrLarger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is not set.  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNoSet {
            get {
                return ResourceManager.GetString("ErrNoSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The selected data on X axis is same as the one on Y axis. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSameAxis {
            get {
                return ResourceManager.GetString("ErrSameAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not save {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSaveFile {
            get {
                return ResourceManager.GetString("ErrSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} should be set {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSetNumber {
            get {
                return ResourceManager.GetString("ErrSetNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} should be set {1} or more. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSetNumberMore {
            get {
                return ResourceManager.GetString("ErrSetNumberMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} should be smaller than {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSmaller {
            get {
                return ResourceManager.GetString("ErrSmaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Finished to execute the {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InfoFinishExecute {
            get {
                return ResourceManager.GetString("InfoFinishExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Analysis... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemAnalysis {
            get {
                return ResourceManager.GetString("MenuItemAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Analysis... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemAnalysisWindow {
            get {
                return ResourceManager.GetString("MenuItemAnalysisWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Bifurcation Analysis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemBifurcationAnalysis {
            get {
                return ResourceManager.GetString("MenuItemBifurcationAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load Analysis Parameter ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemLoadAnalysisCond {
            get {
                return ResourceManager.GetString("MenuItemLoadAnalysisCond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load Analysis Result ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemLoadAnalysisResult {
            get {
                return ResourceManager.GetString("MenuItemLoadAnalysisResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Parameter Estimation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemParameterEstimation {
            get {
                return ResourceManager.GetString("MenuItemParameterEstimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Robust Analysis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemRobustAnalysis {
            get {
                return ResourceManager.GetString("MenuItemRobustAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Analysis Parameter ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemSaveAnalysisCond {
            get {
                return ResourceManager.GetString("MenuItemSaveAnalysisCond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Analysis Result ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemSaveAnalysisResult {
            get {
                return ResourceManager.GetString("MenuItemSaveAnalysisResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Sensitivity Analysis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemSensitivityAnalysis {
            get {
                return ResourceManager.GetString("MenuItemSensitivityAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop Analysis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemStopAnalysis {
            get {
                return ResourceManager.GetString("MenuItemStopAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The absolute perturbation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameAbsolutePert {
            get {
                return ResourceManager.GetString("NameAbsolutePert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   bifurcation analysis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameBifurcation {
            get {
                return ResourceManager.GetString("NameBifurcation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The estimation formulator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameEstimationForm {
            get {
                return ResourceManager.GetString("NameEstimationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The number of generation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameGenerationNum {
            get {
                return ResourceManager.GetString("NameGenerationNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The number of samples for FFT に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameMaxSample {
            get {
                return ResourceManager.GetString("NameMaxSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The observed data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameObservedData {
            get {
                return ResourceManager.GetString("NameObservedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The parameter data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameParameterData {
            get {
                return ResourceManager.GetString("NameParameterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   parameter estimation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameParameterEstimate {
            get {
                return ResourceManager.GetString("NameParameterEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The number of populations に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NamePopulation {
            get {
                return ResourceManager.GetString("NamePopulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The relative perturbation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameRelativePert {
            get {
                return ResourceManager.GetString("NameRelativePert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   robust analysis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameRobustAnalysis {
            get {
                return ResourceManager.GetString("NameRobustAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   sensitivity analysis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameSensAnalysis {
            get {
                return ResourceManager.GetString("NameSensAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The simulation time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameSimulationTime {
            get {
                return ResourceManager.GetString("NameSimulationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The number of step に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameStepNum {
            get {
                return ResourceManager.GetString("NameStepNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reflect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReflectMenuText {
            get {
                return ResourceManager.GetString("ReflectMenuText", resourceCulture);
            }
        }
    }
}
