//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.1433
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcellLib.Analysis {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResAnalysis {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResAnalysis() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EcellLib.Analysis.MessageResAnalysis", typeof(MessageResAnalysis).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Do you want to close this window? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmClose {
            get {
                return ResourceManager.GetString("ConfirmClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to stop the analysis? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmStopAnalysis {
            get {
                return ResourceManager.GetString("ConfirmStopAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The absolute perturbation is lager than 0.0. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrAbsolutePert {
            get {
                return ResourceManager.GetString("ErrAbsolutePert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fail to execute the robust analysis. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrAnalysis {
            get {
                return ResourceManager.GetString("ErrAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are any error job. Do you want to show the result? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrFindErrorJob {
            get {
                return ResourceManager.GetString("ErrFindErrorJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The number of generation is lager than 0. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrGenerationNumPositive {
            get {
                return ResourceManager.GetString("ErrGenerationNumPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are invalid properties in execution parameters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrInputReflect {
            get {
                return ResourceManager.GetString("ErrInputReflect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are invalid properties in the selected parameter file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrLoadParam {
            get {
                return ResourceManager.GetString("ErrLoadParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t find the checked parameter for judgment. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNotCheckParam {
            get {
                return ResourceManager.GetString("ErrNotCheckParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t get the observed parameter. Please set at least one property. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrObservProp {
            get {
                return ResourceManager.GetString("ErrObservProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are invalid parameters. Please check Number of sample, Simulation Time or Check window size. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrOutParam {
            get {
                return ResourceManager.GetString("ErrOutParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get the exception while the prameter file is output. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrOutParamFile {
            get {
                return ResourceManager.GetString("ErrOutParamFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The max number of input is over に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrOverMax {
            get {
                return ResourceManager.GetString("ErrOverMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t get the parameter of property. Please set at least one property. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrParamProp1 {
            get {
                return ResourceManager.GetString("ErrParamProp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t get the parameter of property. Please set at least two property. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrParamProp2 {
            get {
                return ResourceManager.GetString("ErrParamProp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The numner of population is lager than 0. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrPopulationNumPositive {
            get {
                return ResourceManager.GetString("ErrPopulationNumPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of sample, Simulation Time or Check window size should be positive number. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrPosValue {
            get {
                return ResourceManager.GetString("ErrPosValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t find the parameter as random parameter. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrRandParam {
            get {
                return ResourceManager.GetString("ErrRandParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The relative perturbation is lager than 0.0. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrRelativePert {
            get {
                return ResourceManager.GetString("ErrRelativePert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The selected data on X axis is same as the one on Y axis. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSameAxis {
            get {
                return ResourceManager.GetString("ErrSameAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The number of samples is larger than 0, に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSampleNumPositive {
            get {
                return ResourceManager.GetString("ErrSampleNumPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The simulation time is lager than 0.0. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSimTimeUnder {
            get {
                return ResourceManager.GetString("ErrSimTimeUnder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The step is lager than and equal 1. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrStepUnder {
            get {
                return ResourceManager.GetString("ErrStepUnder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Finished to execute the parameter estimation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FinishPAnalysis {
            get {
                return ResourceManager.GetString("FinishPAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Finished to execute the robust analysis. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FinishRAnalysis {
            get {
                return ResourceManager.GetString("FinishRAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Finished to execute the sensitivity analysis. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FinishSAnalysis {
            get {
                return ResourceManager.GetString("FinishSAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Analysis... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemAnalysis {
            get {
                return ResourceManager.GetString("MenuItemAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;AnalysisWindow... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemAnalysisWindow {
            get {
                return ResourceManager.GetString("MenuItemAnalysisWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Parameter Estimation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemParameterEstimation {
            get {
                return ResourceManager.GetString("MenuItemParameterEstimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Robust Analysis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemRobustAnalysis {
            get {
                return ResourceManager.GetString("MenuItemRobustAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Sensitivity Analysis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemSensitivityAnalysis {
            get {
                return ResourceManager.GetString("MenuItemSensitivityAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reflect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReflectMenuText {
            get {
                return ResourceManager.GetString("ReflectMenuText", resourceCulture);
            }
        }
    }
}
