//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.3603
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecell.IDE {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ecell.IDE.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add Property に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonAddProperty {
            get {
                return ResourceManager.GetString("ButtonAddProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonDeleteProperty {
            get {
                return ResourceManager.GetString("ButtonDeleteProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to merge the components into the supersystem? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmMerge {
            get {
                return ResourceManager.GetString("ConfirmMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create Variable References. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogToolTipAddVar {
            get {
                return ResourceManager.GetString("DialogToolTipAddVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Variable References. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogToolTipDeleteVar {
            get {
                return ResourceManager.GetString("DialogToolTipDeleteVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot add the property. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrAddProperty {
            get {
                return ResourceManager.GetString("ErrAddProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The property of the same name already exists. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrAlreadyExist {
            get {
                return ResourceManager.GetString("ErrAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} already exists in this VariableReferenceList. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrExistVariableRef {
            get {
                return ResourceManager.GetString("ErrExistVariableRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot obtain the properties of Entity {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrGetProp {
            get {
                return ResourceManager.GetString("ErrGetProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID string is not valid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrInvalidID {
            get {
                return ResourceManager.GetString("ErrInvalidID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value is not valid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrInvalidValue {
            get {
                return ResourceManager.GetString("ErrInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot load the file {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrLoadFile {
            get {
                return ResourceManager.GetString("ErrLoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please input an integer value for coefficient. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNoNumber {
            get {
                return ResourceManager.GetString("ErrNoNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No target is selected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNoSelectTarget {
            get {
                return ResourceManager.GetString("ErrNoSelectTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select the Variable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNoSelectVar {
            get {
                return ResourceManager.GetString("ErrNoSelectVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The {0} is not set. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNoSet {
            get {
                return ResourceManager.GetString("ErrNoSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot find the set system {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNoSystem {
            get {
                return ResourceManager.GetString("ErrNoSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is the reserved name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrReserved {
            get {
                return ResourceManager.GetString("ErrReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot set the property of Entity {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSetProp {
            get {
                return ResourceManager.GetString("ErrSetProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Merge into supersystem に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MergeSystem {
            get {
                return ResourceManager.GetString("MergeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameExecute {
            get {
                return ResourceManager.GetString("NameExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   property name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameProperty {
            get {
                return ResourceManager.GetString("NameProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input the name of DM whose suffix is &quot;Process&quot; or &quot;Stepper&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarnDMName {
            get {
                return ResourceManager.GetString("WarnDMName", resourceCulture);
            }
        }
    }
}
