//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.3603
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecell.UI.Components {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ecell.UI.Components.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Competitive inhibition に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMPETITIVE {
            get {
                return ResourceManager.GetString("COMPETITIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Degradation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DEGRADATION {
            get {
                return ResourceManager.GetString("DEGRADATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to convert formula. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrConvertFormula {
            get {
                return ResourceManager.GetString("ErrConvertFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Michaelis-Menten に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MICHAELIS {
            get {
                return ResourceManager.GetString("MICHAELIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Noncompetitive inhibition に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NOCOMPETITIVE {
            get {
                return ResourceManager.GetString("NOCOMPETITIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Primary reaction に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PRIMARYREACTION {
            get {
                return ResourceManager.GetString("PRIMARYREACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Secondary reaction に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SECONDARYREACTION {
            get {
                return ResourceManager.GetString("SECONDARYREACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uncompetitive inhibition に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UNCOMPETITIVE {
            get {
                return ResourceManager.GetString("UNCOMPETITIVE", resourceCulture);
            }
        }
    }
}
