//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.832
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcellLib.Simulation {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResSimulation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResSimulation() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EcellLib.Simulation.MessageResSimulation", typeof(MessageResSimulation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Simulation is running. Would you reset the simulation? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmSetup {
            get {
                return ResourceManager.GetString("ConfirmSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This name already exists. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrAlready {
            get {
                return ResourceManager.GetString("ErrAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not select this item. Please select another item. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrComboIndChange {
            get {
                return ResourceManager.GetString("ErrComboIndChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not delete the default parameter. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrDelDefParam {
            get {
                return ResourceManager.GetString("ErrDelDefParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not delete the selected parameter. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrDelParam {
            get {
                return ResourceManager.GetString("ErrDelParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not delete the stepper.  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrDelStep {
            get {
                return ResourceManager.GetString("ErrDelStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Format error. There are invalid characters, に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrIDNG {
            get {
                return ResourceManager.GetString("ErrIDNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are any invalid parameters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrInvalidParam {
            get {
                return ResourceManager.GetString("ErrInvalidParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No input the name. Please input the name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNoInput {
            get {
                return ResourceManager.GetString("ErrNoInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please input the max size of disk. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNoInputDisk {
            get {
                return ResourceManager.GetString("ErrNoInputDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please input the interval of log. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNoInputSec {
            get {
                return ResourceManager.GetString("ErrNoInputSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please input the interval of log. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNoInputStep {
            get {
                return ResourceManager.GetString("ErrNoInputStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please input how to act when disk is full. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNoSelectAct {
            get {
                return ResourceManager.GetString("ErrNoSelectAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please input how to set the max size of disk. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNoSelectDisk {
            get {
                return ResourceManager.GetString("ErrNoSelectDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please set the policy of logging. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNoSelectLog {
            get {
                return ResourceManager.GetString("ErrNoSelectLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get exception while system reset simulation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrReset {
            get {
                return ResourceManager.GetString("ErrReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get exception while system run simulation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrRunning {
            get {
                return ResourceManager.GetString("ErrRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get exception while system step simulation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrStep {
            get {
                return ResourceManager.GetString("ErrStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get exception while system suspend simulation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSuspend {
            get {
                return ResourceManager.GetString("ErrSuspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fail to update the simulation parameters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrUpdatELog {
            get {
                return ResourceManager.GetString("ErrUpdatELog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Run に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemRun {
            get {
                return ResourceManager.GetString("MenuItemRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Simulation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemSetupSim {
            get {
                return ResourceManager.GetString("MenuItemSetupSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   R&amp;eset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemStop {
            get {
                return ResourceManager.GetString("MenuItemStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Suspend に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemSuspend {
            get {
                return ResourceManager.GetString("MenuItemSuspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Stepper に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewStepperText {
            get {
                return ResourceManager.GetString("NewStepperText", resourceCulture);
            }
        }
    }
}
