//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.3603
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecell.IDE.Plugins.Simulation {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ecell.IDE.Plugins.Simulation.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Are you sure to override the simulation parameter sets[ {0} ]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmOverride {
            get {
                return ResourceManager.GetString("ConfirmOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to reset the simulation? The edited paramters is reset while the simulation is executed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmReset {
            get {
                return ResourceManager.GetString("ConfirmReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create new simulation configration に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogToolTipCreSim {
            get {
                return ResourceManager.GetString("DialogToolTipCreSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create the new Stepper に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogToolTipCreStepper {
            get {
                return ResourceManager.GetString("DialogToolTipCreStepper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete this configration に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogToolTipDeleteSim {
            get {
                return ResourceManager.GetString("DialogToolTipDeleteSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete this Stepper に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogToolTipDelStepper {
            get {
                return ResourceManager.GetString("DialogToolTipDelStepper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is already exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrAlreadyExist {
            get {
                return ResourceManager.GetString("ErrAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not delete DefaultSets. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrDelDefault {
            get {
                return ResourceManager.GetString("ErrDelDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   At least a parameter set is required in the project. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrDelParam {
            get {
                return ResourceManager.GetString("ErrDelParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   At least a Stepper is required in the model. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrDelStep {
            get {
                return ResourceManager.GetString("ErrDelStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to export the simulation parameter [{0}]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrExportSim {
            get {
                return ResourceManager.GetString("ErrExportSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID string is not valid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrIDNG {
            get {
                return ResourceManager.GetString("ErrIDNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to import the simulation parameter [{0}]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrImportSim {
            get {
                return ResourceManager.GetString("ErrImportSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value is not valid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrInvalidValue {
            get {
                return ResourceManager.GetString("ErrInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nothing is input in {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNoInput {
            get {
                return ResourceManager.GetString("ErrNoInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not import DefaultSets. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorImportDefault {
            get {
                return ResourceManager.GetString("ErrorImportDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is at least an Entity that refers to the Stepper {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrStepperStillInUse {
            get {
                return ResourceManager.GetString("ErrStepperStillInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot update the simulation parameters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrUpdateLog {
            get {
                return ResourceManager.GetString("ErrUpdateLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The simulation parameter [{0}] is exported. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InfoExportSim {
            get {
                return ResourceManager.GetString("InfoExportSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The simulation parameter [{0}] is imported. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InfoImportSim {
            get {
                return ResourceManager.GetString("InfoImportSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Run に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemRun {
            get {
                return ResourceManager.GetString("MenuItemRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Simulation... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemSetupSim {
            get {
                return ResourceManager.GetString("MenuItemSetupSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   S&amp;tep に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemStep {
            get {
                return ResourceManager.GetString("MenuItemStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stepping model に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemSteppingModel {
            get {
                return ResourceManager.GetString("MenuItemSteppingModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   R&amp;eset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemStop {
            get {
                return ResourceManager.GetString("MenuItemStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Suspend に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemSuspend {
            get {
                return ResourceManager.GetString("MenuItemSuspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back to one simulation action. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuToolTipBack {
            get {
                return ResourceManager.GetString("MenuToolTipBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Foward to one simulation action. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuToolTipFoward {
            get {
                return ResourceManager.GetString("MenuToolTipFoward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the parameter using in simulation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuToolTipParamCombo {
            get {
                return ResourceManager.GetString("MenuToolTipParamCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset the simulation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuToolTipReset {
            get {
                return ResourceManager.GetString("MenuToolTipReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run the simulation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuToolTipRun {
            get {
                return ResourceManager.GetString("MenuToolTipRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Step the simulation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuToolTipStep {
            get {
                return ResourceManager.GetString("MenuToolTipStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input the step. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuToolTipStepText {
            get {
                return ResourceManager.GetString("MenuToolTipStepText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose unit of the step. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuToolTipStepUnitCombo {
            get {
                return ResourceManager.GetString("MenuToolTipStepUnitCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop the simulation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuToolTipSuspend {
            get {
                return ResourceManager.GetString("MenuToolTipSuspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logfile size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameMaxSize {
            get {
                return ResourceManager.GetString("NameMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameName {
            get {
                return ResourceManager.GetString("NameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sec に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameSec {
            get {
                return ResourceManager.GetString("NameSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Simulation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameSimulation {
            get {
                return ResourceManager.GetString("NameSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Step に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameStep {
            get {
                return ResourceManager.GetString("NameStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The number of steps に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameStepNum {
            get {
                return ResourceManager.GetString("NameStepNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The waiting time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameWaitTime {
            get {
                return ResourceManager.GetString("NameWaitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Stepper に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewStepperText {
            get {
                return ResourceManager.GetString("NewStepperText", resourceCulture);
            }
        }
    }
}
