//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.1378
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecell.IDE.Plugins.Simulation {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResSimulation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResSimulation() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ecell.IDE.Plugins.Simulation.MessageResSimulation", typeof(MessageResSimulation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Simulation is running. Would you reset the simulation? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmSetup {
            get {
                return ResourceManager.GetString("ConfirmSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not delete the selected parameter {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrDelParam {
            get {
                return ResourceManager.GetString("ErrDelParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not delete the stepper.  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrDelStep {
            get {
                return ResourceManager.GetString("ErrDelStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are any invalid characters in ID. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrIDNG {
            get {
                return ResourceManager.GetString("ErrIDNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are any invalid parameters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrInvalidValue {
            get {
                return ResourceManager.GetString("ErrInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No input [ {0} ]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNoInput {
            get {
                return ResourceManager.GetString("ErrNoInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not update the simulation parameters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrUpdateLog {
            get {
                return ResourceManager.GetString("ErrUpdateLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Run に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemRun {
            get {
                return ResourceManager.GetString("MenuItemRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Simulation... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemSetupSim {
            get {
                return ResourceManager.GetString("MenuItemSetupSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   R&amp;eset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemStop {
            get {
                return ResourceManager.GetString("MenuItemStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Suspend に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemSuspend {
            get {
                return ResourceManager.GetString("MenuItemSuspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Stepper に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewStepperText {
            get {
                return ResourceManager.GetString("NewStepperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolTipRun {
            get {
                return ResourceManager.GetString("ToolTipRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Step に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolTipStep {
            get {
                return ResourceManager.GetString("ToolTipStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolTipStop {
            get {
                return ResourceManager.GetString("ToolTipStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Suspend に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolTipSuspend {
            get {
                return ResourceManager.GetString("ToolTipSuspend", resourceCulture);
            }
        }
    }
}
