//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.1433
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcellLib.PathwayWindow.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResPathway {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResPathway() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EcellLib.PathwayWindow.Resources.MessageResPathway", typeof(MessageResPathway).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Process &lt;-&gt; Variable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuBidirArrow {
            get {
                return ResourceManager.GetString("CanvasMenuBidirArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Layer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuChangeLayer {
            get {
                return ResourceManager.GetString("CanvasMenuChangeLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Constant に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuConstantLine {
            get {
                return ResourceManager.GetString("CanvasMenuConstantLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Copy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuCopy {
            get {
                return ResourceManager.GetString("CanvasMenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create Logger に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuCreateLogger {
            get {
                return ResourceManager.GetString("CanvasMenuCreateLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cu&amp;t に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuCut {
            get {
                return ResourceManager.GetString("CanvasMenuCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuDelete {
            get {
                return ResourceManager.GetString("CanvasMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Logger に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuDeleteLogger {
            get {
                return ResourceManager.GetString("CanvasMenuDeleteLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Layout に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuLayout {
            get {
                return ResourceManager.GetString("CanvasMenuLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process &lt;- Variable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuLeftArrow {
            get {
                return ResourceManager.GetString("CanvasMenuLeftArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Merge to supersystem に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuMerge {
            get {
                return ResourceManager.GetString("CanvasMenuMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Paste に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuPaste {
            get {
                return ResourceManager.GetString("CanvasMenuPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process -&gt; Variable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanvasMenuRightArrow {
            get {
                return ResourceManager.GetString("CanvasMenuRightArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure merge the component in system to upper system. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmMerge {
            get {
                return ResourceManager.GetString("ConfirmMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Animation Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTextAnimationSetting {
            get {
                return ResourceManager.GetString("DialogTextAnimationSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Background Brush に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTextBackgroundBrush {
            get {
                return ResourceManager.GetString("DialogTextBackgroundBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edge Brush に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTextEdgeBrush {
            get {
                return ResourceManager.GetString("DialogTextEdgeBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edge Width に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTextEdgeWidth {
            get {
                return ResourceManager.GetString("DialogTextEdgeWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTextEditMode {
            get {
                return ResourceManager.GetString("DialogTextEditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logarithmic に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTextLogarithmic {
            get {
                return ResourceManager.GetString("DialogTextLogarithmic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max Edge Width に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTextMaxEdgeWidth {
            get {
                return ResourceManager.GetString("DialogTextMaxEdgeWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NG Brush に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTextNGBrush {
            get {
                return ResourceManager.GetString("DialogTextNGBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Normal Edge に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTextNormalEdge {
            get {
                return ResourceManager.GetString("DialogTextNormalEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Property Brush に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTextPropertyBrush {
            get {
                return ResourceManager.GetString("DialogTextPropertyBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Threshold High に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTextThresholdHigh {
            get {
                return ResourceManager.GetString("DialogTextThresholdHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Threshold Low に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTextThresholdLow {
            get {
                return ResourceManager.GetString("DialogTextThresholdLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTextViewMode {
            get {
                return ResourceManager.GetString("DialogTextViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not add the object. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrAddObj {
            get {
                return ResourceManager.GetString("ErrAddObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not find the added object. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrAddObjNot {
            get {
                return ResourceManager.GetString("ErrAddObjNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Already connected ! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrAlrConnect {
            get {
                return ResourceManager.GetString("ErrAlrConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///    has already existed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrAlrExist {
            get {
                return ResourceManager.GetString("ErrAlrExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ComponentSettings.xml is imcomplete for the following reason に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrCompInvalid {
            get {
                return ResourceManager.GetString("ErrCompInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default process was not found in the ComponentSettings.xml file, so hard coded one will be used instead.\n\n に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrComProcess {
            get {
                return ResourceManager.GetString("ErrComProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default system was not found in the ComponentSettings.xml file, so hard coded one will be used instead.\n\n に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrComSystem {
            get {
                return ResourceManager.GetString("ErrComSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default variable was not found in the ComponentSettings.xml file, so hard coded one will be used instead.\n\n に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrComVariable {
            get {
                return ResourceManager.GetString("ErrComVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fail to convert the information to component object. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrCreateKind {
            get {
                return ResourceManager.GetString("ErrCreateKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not delete the root system. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrDelRoot {
            get {
                return ResourceManager.GetString("ErrDelRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No set the object id. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrKeyNot {
            get {
                return ResourceManager.GetString("ErrKeyNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Layer does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrLayerNot {
            get {
                return ResourceManager.GetString("ErrLayerNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t execute this layout due to an unexpected error, sorry. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrLayout {
            get {
                return ResourceManager.GetString("ErrLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fail to load EcellObject position settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrLoadLEML {
            get {
                return ResourceManager.GetString("ErrLoadLEML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not merge the component to the upper system. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrMerge {
            get {
                return ResourceManager.GetString("ErrMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t find ComponentSettings.xml file in the &lt;ECell-HOME&gt;&quot;\\plugins\\pathway directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNotComXml {
            get {
                return ResourceManager.GetString("ErrNotComXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Canvas ID is not set for  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNotSetCanvas {
            get {
                return ResourceManager.GetString("ErrNotSetCanvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not create an object outside the root system に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrOutRoot {
            get {
                return ResourceManager.GetString("ErrOutRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A system can&apos;t be overlapping other systems に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrOverSystem {
            get {
                return ResourceManager.GetString("ErrOverSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are the objects that have the same ID. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSameObj {
            get {
                return ResourceManager.GetString("ErrSameObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fail to save EcellObject position settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSaveLEML {
            get {
                return ResourceManager.GetString("ErrSaveLEML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no space to create new system. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSystemOverlap {
            get {
                return ResourceManager.GetString("ErrSystemOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toolbox is available only with a select mode. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrToolBox {
            get {
                return ResourceManager.GetString("ErrToolBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The added object have the unknown type. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrUnknowType {
            get {
                return ResourceManager.GetString("ErrUnknowType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input new Layer name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayerDialogMessage {
            get {
                return ResourceManager.GetString("LayerDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LayerNameInputDialog に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayerDialogTitle {
            get {
                return ResourceManager.GetString("LayerDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Layer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayerMenuChange {
            get {
                return ResourceManager.GetString("LayerMenuChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create Layer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayerMenuCreate {
            get {
                return ResourceManager.GetString("LayerMenuCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Layer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayerMenuDelete {
            get {
                return ResourceManager.GetString("LayerMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Merge Layer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayerMenuMerge {
            get {
                return ResourceManager.GetString("LayerMenuMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move to back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayerMenuMoveBack {
            get {
                return ResourceManager.GetString("LayerMenuMoveBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move to front に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayerMenuMoveFront {
            get {
                return ResourceManager.GetString("LayerMenuMoveFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename Layer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayerMenuRename {
            get {
                return ResourceManager.GetString("LayerMenuRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select nodes under... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayerMenuSelectNodes {
            get {
                return ResourceManager.GetString("LayerMenuSelectNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemEdit {
            get {
                return ResourceManager.GetString("MenuItemEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export Graphics. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemExport {
            get {
                return ResourceManager.GetString("MenuItemExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export SVG format... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemExportSVG {
            get {
                return ResourceManager.GetString("MenuItemExportSVG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemFile {
            get {
                return ResourceManager.GetString("MenuItemFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Layout に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemLayout {
            get {
                return ResourceManager.GetString("MenuItemLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pathway Settings... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemSetup {
            get {
                return ResourceManager.GetString("MenuItemSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show &amp;IDs(Pathway) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemShowID {
            get {
                return ResourceManager.GetString("MenuItemShowID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;View に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemView {
            get {
                return ResourceManager.GetString("MenuItemView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemViewMode {
            get {
                return ResourceManager.GetString("MenuItemViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export Graphics. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuToolTipExport {
            get {
                return ResourceManager.GetString("MenuToolTipExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export SVG format. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuToolTipExportSVG {
            get {
                return ResourceManager.GetString("MenuToolTipExportSVG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show PropertyDialog of PathwayWindow. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuToolTipSetup {
            get {
                return ResourceManager.GetString("MenuToolTipSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Visibility of Node&apos;s name of each pathway object. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuToolTipShowID {
            get {
                return ResourceManager.GetString("MenuToolTipShowID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change view mode of canvas. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuToolTipViewMode {
            get {
                return ResourceManager.GetString("MenuToolTipViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select at least one node to layout に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgLayoutNoNode {
            get {
                return ResourceManager.GetString("MsgLayoutNoNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create constant references. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolButtonAddConstant {
            get {
                return ResourceManager.GetString("ToolButtonAddConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create mutual reactions. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolButtonAddMutualReaction {
            get {
                return ResourceManager.GetString("ToolButtonAddMutualReaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create oneway reactions. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolButtonAddOnewayReaction {
            get {
                return ResourceManager.GetString("ToolButtonAddOnewayReaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create new processes. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolButtonCreateProcess {
            get {
                return ResourceManager.GetString("ToolButtonCreateProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create new systems. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolButtonCreateSystem {
            get {
                return ResourceManager.GetString("ToolButtonCreateSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create Text objent. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolButtonCreateText {
            get {
                return ResourceManager.GetString("ToolButtonCreateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create new variables. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolButtonCreateVariable {
            get {
                return ResourceManager.GetString("ToolButtonCreateVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move canvas. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolButtonMoveCanvas {
            get {
                return ResourceManager.GetString("ToolButtonMoveCanvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Mode. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolButtonSelectMode {
            get {
                return ResourceManager.GetString("ToolButtonSelectMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom in に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolButtonZoomIn {
            get {
                return ResourceManager.GetString("ToolButtonZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom out に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolButtonZoomOut {
            get {
                return ResourceManager.GetString("ToolButtonZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Layer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowLayer {
            get {
                return ResourceManager.GetString("WindowLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Overview に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowOverview {
            get {
                return ResourceManager.GetString("WindowOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Network に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowPathway {
            get {
                return ResourceManager.GetString("WindowPathway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toolbox に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowToolbox {
            get {
                return ResourceManager.GetString("WindowToolbox", resourceCulture);
            }
        }
    }
}
