//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.1433
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecell.IDE.Plugins.TracerWindow {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ecell.IDE.Plugins.TracerWindow.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Do you really want to close this window? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmClose {
            get {
                return ResourceManager.GetString("ConfirmClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are no numerical data. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrInputData {
            get {
                return ResourceManager.GetString("ErrInputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Finish to save the simulation log successfully. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FinishSave {
            get {
                return ResourceManager.GetString("FinishSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemDeleteText {
            get {
                return ResourceManager.GetString("MenuItemDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemImportData {
            get {
                return ResourceManager.GetString("MenuItemImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Graph... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemShowSaveTraceText {
            get {
                return ResourceManager.GetString("MenuItemShowSaveTraceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Graph Setup... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemShowTraceSetupText {
            get {
                return ResourceManager.GetString("MenuItemShowTraceSetupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create New &amp;Graph... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemShowTraceText {
            get {
                return ResourceManager.GetString("MenuItemShowTraceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Graph に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TracerWindow {
            get {
                return ResourceManager.GetString("TracerWindow", resourceCulture);
            }
        }
    }
}
