//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.1433
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecell {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ecell.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Are you sure you want to merge the components to the supersystem? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmMerge {
            get {
                return ResourceManager.GetString("ConfirmMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change to a property that cannot be set during  simulation is attempted. Do you want to stop the simulation? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmReset {
            get {
                return ResourceManager.GetString("ConfirmReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot add {0} ({1}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrAdd {
            get {
                return ResourceManager.GetString("ErrAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The ID of the root System cannot be changed.  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrChangeRoot {
            get {
                return ResourceManager.GetString("ErrChangeRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not close the project ({0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrClosePrj {
            get {
                return ResourceManager.GetString("ErrClosePrj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The selected process cannot be used in combination with the stepper. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrCombiStepProc {
            get {
                return ResourceManager.GetString("ErrCombiStepProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot compile this DM({0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrCompile {
            get {
                return ResourceManager.GetString("ErrCompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot copy the object ({0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrCopy {
            get {
                return ResourceManager.GetString("ErrCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot create the file {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrCreFile {
            get {
                return ResourceManager.GetString("ErrCreFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot create the project ({0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrCrePrj {
            get {
                return ResourceManager.GetString("ErrCrePrj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot create the simulation parameter ({0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrCreSimParam {
            get {
                return ResourceManager.GetString("ErrCreSimParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot delete ({0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrDelete {
            get {
                return ResourceManager.GetString("ErrDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot delete the root system. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrDelRoot {
            get {
                return ResourceManager.GetString("ErrDelRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Entity {0} already exists in this project. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrExistObj {
            get {
                return ResourceManager.GetString("ErrExistObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Simulation parameter {0} already exists in this project. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrExistSimParam {
            get {
                return ResourceManager.GetString("ErrExistSimParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stepper {0} already exists in this project. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrExistStepper {
            get {
                return ResourceManager.GetString("ErrExistStepper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot find Entity {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrFindEnt {
            get {
                return ResourceManager.GetString("ErrFindEnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot find the file {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrFindFile {
            get {
                return ResourceManager.GetString("ErrFindFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot retrieve the log data. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrGetLogData {
            get {
                return ResourceManager.GetString("ErrGetLogData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot obtain the properties of Entity {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrGetProp {
            get {
                return ResourceManager.GetString("ErrGetProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot initialize the simulator. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrInitSim {
            get {
                return ResourceManager.GetString("ErrInitSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FullID string is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrInvalidID {
            get {
                return ResourceManager.GetString("ErrInvalidID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot load the file {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrLoadFile {
            get {
                return ResourceManager.GetString("ErrLoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot load the model {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrLoadModel {
            get {
                return ResourceManager.GetString("ErrLoadModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot load the plugin {0} (location: {1}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrLoadPlugin {
            get {
                return ResourceManager.GetString("ErrLoadPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot load the project {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrLoadPrj {
            get {
                return ResourceManager.GetString("ErrLoadPrj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is not set. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNoSet {
            get {
                return ResourceManager.GetString("ErrNoSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot create the Stepper {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNotCreStepper {
            get {
                return ResourceManager.GetString("ErrNotCreStepper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is not installed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNotInstall {
            get {
                return ResourceManager.GetString("ErrNotInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannotget the property value {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrPropData {
            get {
                return ResourceManager.GetString("ErrPropData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot reset the simulation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrResetSim {
            get {
                return ResourceManager.GetString("ErrResetSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Simulation is already started. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrRunning {
            get {
                return ResourceManager.GetString("ErrRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot start the simulation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrRunSim {
            get {
                return ResourceManager.GetString("ErrRunSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot save the action file {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSaveAct {
            get {
                return ResourceManager.GetString("ErrSaveAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot save the log. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSaveLog {
            get {
                return ResourceManager.GetString("ErrSaveLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot save the model {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSaveModel {
            get {
                return ResourceManager.GetString("ErrSaveModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot save the project {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSavePrj {
            get {
                return ResourceManager.GetString("ErrSavePrj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot save the script file {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSaveScript {
            get {
                return ResourceManager.GetString("ErrSaveScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot set the initial parameters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSetInitParam {
            get {
                return ResourceManager.GetString("ErrSetInitParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot set the property of entity {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSetProp {
            get {
                return ResourceManager.GetString("ErrSetProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot set the simulation parameter. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSetSimParam {
            get {
                return ResourceManager.GetString("ErrSetSimParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot suspend the simulation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSuspendSim {
            get {
                return ResourceManager.GetString("ErrSuspendSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is added ({1}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InfoAdd {
            get {
                return ResourceManager.GetString("InfoAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Project {0} is closed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InfoClose {
            get {
                return ResourceManager.GetString("InfoClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compile[{0}] is finished. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InfoCompile {
            get {
                return ResourceManager.GetString("InfoCompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Simulation parameter {0} was created. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InfoCreSim {
            get {
                return ResourceManager.GetString("InfoCreSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is deleted ({1}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InfoDel {
            get {
                return ResourceManager.GetString("InfoDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading plugin {0}... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InfoLoadPlugin {
            get {
                return ResourceManager.GetString("InfoLoadPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The simulation was terminated at [{0}]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InfoResetSim {
            get {
                return ResourceManager.GetString("InfoResetSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Model {0} is saved. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InfoSaveModel {
            get {
                return ResourceManager.GetString("InfoSaveModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Project {0} is saved. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InfoSavePrj {
            get {
                return ResourceManager.GetString("InfoSavePrj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current simulation parameter is set to {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InfoSimParamSet {
            get {
                return ResourceManager.GetString("InfoSimParamSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The simulation was suspended at [{0}]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InfoSuspend {
            get {
                return ResourceManager.GetString("InfoSuspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Model に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameModel {
            get {
                return ResourceManager.GetString("NameModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Simulation parameter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameSimParam {
            get {
                return ResourceManager.GetString("NameSimParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Simulation result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameSimResult {
            get {
                return ResourceManager.GetString("NameSimResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Project root folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameWorkDir {
            get {
                return ResourceManager.GetString("NameWorkDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Simulation is restarted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SimulationRestarted {
            get {
                return ResourceManager.GetString("SimulationRestarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Simulation is started. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SimulationStarted {
            get {
                return ResourceManager.GetString("SimulationStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Some Dynamic Modules (DM) cannot be loaded. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarnLoadDM {
            get {
                return ResourceManager.GetString("WarnLoadDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is loaded now. Please move the file from {1
        ///} to {0} after the model was closed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarnMoveDM {
            get {
                return ResourceManager.GetString("WarnMoveDM", resourceCulture);
            }
        }
    }
}
