//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.1433
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcellLib {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResLib {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResLib() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EcellLib.MessageResLib", typeof(MessageResLib).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Are you sure to merge the components to the upper system? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmMerge {
            get {
                return ResourceManager.GetString("ConfirmMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Simulation is running. Do you want to reset the simulation? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmReset {
            get {
                return ResourceManager.GetString("ConfirmReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not add the {0} ({1}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrAdd {
            get {
                return ResourceManager.GetString("ErrAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not close the project ({0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrClosePrj {
            get {
                return ResourceManager.GetString("ErrClosePrj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The selected process cannot be used in combination with the system&apos;s stepper. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrCombiStepProc {
            get {
                return ResourceManager.GetString("ErrCombiStepProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not copy the object [{0}]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrCopy {
            get {
                return ResourceManager.GetString("ErrCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not create the file ({0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrCreFile {
            get {
                return ResourceManager.GetString("ErrCreFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not create the project({0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrCrePrj {
            get {
                return ResourceManager.GetString("ErrCrePrj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not create the simulation parameter({0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrCreSimParam {
            get {
                return ResourceManager.GetString("ErrCreSimParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not delete ({0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrDelete {
            get {
                return ResourceManager.GetString("ErrDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not delete the root system. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrDelRoot {
            get {
                return ResourceManager.GetString("ErrDelRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} already exists in project. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrExistObj {
            get {
                return ResourceManager.GetString("ErrExistObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} already exists in project. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrExistSimParam {
            get {
                return ResourceManager.GetString("ErrExistSimParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} already exists in project. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrExistStepper {
            get {
                return ResourceManager.GetString("ErrExistStepper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} already exists in this VariableReferenceList. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrExistVariableRef {
            get {
                return ResourceManager.GetString("ErrExistVariableRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not find the entity {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrFindEnt {
            get {
                return ResourceManager.GetString("ErrFindEnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not find the file {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrFindFile {
            get {
                return ResourceManager.GetString("ErrFindFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not retrieve the log data. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrGetLogData {
            get {
                return ResourceManager.GetString("ErrGetLogData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not obtain the properties of entity {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrGetProp {
            get {
                return ResourceManager.GetString("ErrGetProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not initialize the simulator. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrInitSim {
            get {
                return ResourceManager.GetString("ErrInitSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are any invalid characters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrInvalidID {
            get {
                return ResourceManager.GetString("ErrInvalidID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not the file [ {0} ]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrLoadFile {
            get {
                return ResourceManager.GetString("ErrLoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not load the model {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrLoadModel {
            get {
                return ResourceManager.GetString("ErrLoadModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not load the project {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrLoadPrj {
            get {
                return ResourceManager.GetString("ErrLoadPrj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please input integer at coefficient and isAccessor. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNoNumber {
            get {
                return ResourceManager.GetString("ErrNoNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select the variable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNoSelectVar {
            get {
                return ResourceManager.GetString("ErrNoSelectVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The {0} is not set. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNoSet {
            get {
                return ResourceManager.GetString("ErrNoSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not create the stepper {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNotCreStepper {
            get {
                return ResourceManager.GetString("ErrNotCreStepper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not print the image of plugin. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrPrint {
            get {
                return ResourceManager.GetString("ErrPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is the reserved name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrReserved {
            get {
                return ResourceManager.GetString("ErrReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not reset the simulation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrResetSim {
            get {
                return ResourceManager.GetString("ErrResetSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Simulation is already running. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrRunning {
            get {
                return ResourceManager.GetString("ErrRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not execute the simulation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrRunSim {
            get {
                return ResourceManager.GetString("ErrRunSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not save the action file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSaveAct {
            get {
                return ResourceManager.GetString("ErrSaveAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not save the log. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSaveLog {
            get {
                return ResourceManager.GetString("ErrSaveLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not save the model {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSaveModel {
            get {
                return ResourceManager.GetString("ErrSaveModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not save the project {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSavePrj {
            get {
                return ResourceManager.GetString("ErrSavePrj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not save the script file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSaveScript {
            get {
                return ResourceManager.GetString("ErrSaveScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not set the initial parameters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSetInitParam {
            get {
                return ResourceManager.GetString("ErrSetInitParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not set the property of entity {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSetProp {
            get {
                return ResourceManager.GetString("ErrSetProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not set the property {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSetPropCommand {
            get {
                return ResourceManager.GetString("ErrSetPropCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not set the simulation parameter. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSetSimParam {
            get {
                return ResourceManager.GetString("ErrSetSimParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not the value of property {0} under the simulation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSimPropData {
            get {
                return ResourceManager.GetString("ErrSimPropData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not suspend the simulation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSuspendSim {
            get {
                return ResourceManager.GetString("ErrSuspendSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not set the policy of logger. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrUpdateLogPol {
            get {
                return ResourceManager.GetString("ErrUpdateLogPol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add the {0} ({1}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InfoAdd {
            get {
                return ResourceManager.GetString("InfoAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close the project ({0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InfoClose {
            get {
                return ResourceManager.GetString("InfoClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create the simulation parameter ({0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InfoCreSim {
            get {
                return ResourceManager.GetString("InfoCreSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete the {0} ({1}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InfoDel {
            get {
                return ResourceManager.GetString("InfoDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset the simulation [{0}]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InfoResetSim {
            get {
                return ResourceManager.GetString("InfoResetSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save the model {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InfoSaveModel {
            get {
                return ResourceManager.GetString("InfoSaveModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save the project {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InfoSavePrj {
            get {
                return ResourceManager.GetString("InfoSavePrj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Suspend the simulation [{0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InfoSuspend {
            get {
                return ResourceManager.GetString("InfoSuspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update the policy of logging {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InfoUpdateLogPol {
            get {
                return ResourceManager.GetString("InfoUpdateLogPol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   simulation parameter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameSimParam {
            get {
                return ResourceManager.GetString("NameSimParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   working directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameWorkDir {
            get {
                return ResourceManager.GetString("NameWorkDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are any process and any stepper that do not exist in DM directory. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarnLoadDM {
            get {
                return ResourceManager.GetString("WarnLoadDM", resourceCulture);
            }
        }
    }
}
