//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.1433
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcellLib {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResLib {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResLib() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EcellLib.MessageResLib", typeof(MessageResLib).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Simulation is running. Would you reset the simulation? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmReset {
            get {
                return ResourceManager.GetString("ConfirmReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get exception while system add the object. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrAdd {
            get {
                return ResourceManager.GetString("ErrAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///    can not be created. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrAddObj {
            get {
                return ResourceManager.GetString("ErrAddObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not find the working directory. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrBaseDir {
            get {
                return ResourceManager.GetString("ErrBaseDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get exception while system update the property of object. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrChange {
            get {
                return ResourceManager.GetString("ErrChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not check the ID. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrCheckID {
            get {
                return ResourceManager.GetString("ErrCheckID", resourceCulture);
            }
        }
        
        /// <summary>
        ///    can not be closed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrClosePrj {
            get {
                return ResourceManager.GetString("ErrClosePrj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This combination of stepper and process is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrCombiStepProc {
            get {
                return ResourceManager.GetString("ErrCombiStepProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not create the ecd file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrCreEcd {
            get {
                return ResourceManager.GetString("ErrCreEcd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not create the eml file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrCreEml {
            get {
                return ResourceManager.GetString("ErrCreEml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to create project {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrCrePrj {
            get {
                return ResourceManager.GetString("ErrCrePrj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not create the simulation parameter. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrCreSimParam {
            get {
                return ResourceManager.GetString("ErrCreSimParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not create the xml file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrCreXml {
            get {
                return ResourceManager.GetString("ErrCreXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not find the current simulation parameter. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrCurParamID {
            get {
                return ResourceManager.GetString("ErrCurParamID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t delete. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrDelete {
            get {
                return ResourceManager.GetString("ErrDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not delete the simulation parameter. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrDeleteSimParam {
            get {
                return ResourceManager.GetString("ErrDeleteSimParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not delete the root system. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrDelRoot {
            get {
                return ResourceManager.GetString("ErrDelRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} already exists in this VariableReferenceList. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrExistID {
            get {
                return ResourceManager.GetString("ErrExistID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} already exists in project. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrExistObj {
            get {
                return ResourceManager.GetString("ErrExistObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} already exists in project. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrExistSimParam {
            get {
                return ResourceManager.GetString("ErrExistSimParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} already exists in project. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrExistStepper {
            get {
                return ResourceManager.GetString("ErrExistStepper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not export to the file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrExportFile {
            get {
                return ResourceManager.GetString("ErrExportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not find the DM directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrFindDmDir {
            get {
                return ResourceManager.GetString("ErrFindDmDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not find entity. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrFindEnt {
            get {
                return ResourceManager.GetString("ErrFindEnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not find the model. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrFindModel {
            get {
                return ResourceManager.GetString("ErrFindModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not find the project. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrFindPrj {
            get {
                return ResourceManager.GetString("ErrFindPrj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not find the project file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrFindPrjFile {
            get {
                return ResourceManager.GetString("ErrFindPrjFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not find the running simulation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrFindRunSim {
            get {
                return ResourceManager.GetString("ErrFindRunSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not find the simulation parameter. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrFindSimParam {
            get {
                return ResourceManager.GetString("ErrFindSimParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not find stepper. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrFindStepper {
            get {
                return ResourceManager.GetString("ErrFindStepper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could find the super system. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrFindSuper {
            get {
                return ResourceManager.GetString("ErrFindSuper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could find the system. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrFindSystem {
            get {
                return ResourceManager.GetString("ErrFindSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not retrieve the log data. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrGetData {
            get {
                return ResourceManager.GetString("ErrGetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not find entities in the model. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrGetEnt {
            get {
                return ResourceManager.GetString("ErrGetEnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not obtain properties. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrGetProp {
            get {
                return ResourceManager.GetString("ErrGetProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not retrieve simulation parameters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrGetSimParams {
            get {
                return ResourceManager.GetString("ErrGetSimParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not find the simulation parameter in model. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrGetStep {
            get {
                return ResourceManager.GetString("ErrGetStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not get the list of system. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrGetSysList {
            get {
                return ResourceManager.GetString("ErrGetSysList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This ID is malformed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrIDMalformed {
            get {
                return ResourceManager.GetString("ErrIDMalformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invarid Full ID. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrIDUnform {
            get {
                return ResourceManager.GetString("ErrIDUnform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not obtain the initial parameters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrInitParam {
            get {
                return ResourceManager.GetString("ErrInitParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not initialize the simulator. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrInitSim {
            get {
                return ResourceManager.GetString("ErrInitSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are invalid characters in ID. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrInvalidID {
            get {
                return ResourceManager.GetString("ErrInvalidID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are any invalid characters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrInvalidName {
            get {
                return ResourceManager.GetString("ErrInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are invalid property in this window, に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrInvalidProp {
            get {
                return ResourceManager.GetString("ErrInvalidProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not load the model. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrLoadModel {
            get {
                return ResourceManager.GetString("ErrLoadModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not load the project. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrLoadPrj {
            get {
                return ResourceManager.GetString("ErrLoadPrj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not load the simulation parameter. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrLoadSimParam {
            get {
                return ResourceManager.GetString("ErrLoadSimParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please input the necessary item. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNoInput {
            get {
                return ResourceManager.GetString("ErrNoInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please input integer at coefficient and isAccessor. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNoNumber {
            get {
                return ResourceManager.GetString("ErrNoNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No select the variable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNoSelect {
            get {
                return ResourceManager.GetString("ErrNoSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///    can not be created. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNotCreStepper {
            get {
                return ResourceManager.GetString("ErrNotCreStepper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is not variable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNotVar {
            get {
                return ResourceManager.GetString("ErrNotVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are the object with null data. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNullData {
            get {
                return ResourceManager.GetString("ErrNullData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not parse the eml file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrParseEml {
            get {
                return ResourceManager.GetString("ErrParseEml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not find the project directory, に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrPrjDir {
            get {
                return ResourceManager.GetString("ErrPrjDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SIZE is the reserved name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrReserveSize {
            get {
                return ResourceManager.GetString("ErrReserveSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not reset the simulation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrResetSim {
            get {
                return ResourceManager.GetString("ErrResetSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Simulation is already running. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrRunning {
            get {
                return ResourceManager.GetString("ErrRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not execute the simulation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrRunSim {
            get {
                return ResourceManager.GetString("ErrRunSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not save the model. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSaveModel {
            get {
                return ResourceManager.GetString("ErrSaveModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not save the null or empty property. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSaveNull {
            get {
                return ResourceManager.GetString("ErrSaveNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not save the project に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSavePrj {
            get {
                return ResourceManager.GetString("ErrSavePrj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not save the simulation parameter. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSaveSim {
            get {
                return ResourceManager.GetString("ErrSaveSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not set the initial parameters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSetInitParam {
            get {
                return ResourceManager.GetString("ErrSetInitParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not set the property of object. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSetProp {
            get {
                return ResourceManager.GetString("ErrSetProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not set the simulation parameter. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSetSimParam {
            get {
                return ResourceManager.GetString("ErrSetSimParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not update the stepper, に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSetStepper {
            get {
                return ResourceManager.GetString("ErrSetStepper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get exception while system show the property editor. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrShowPropEdit {
            get {
                return ResourceManager.GetString("ErrShowPropEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fail to show property editor.\nPlease confirm the property of object.\n に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrShowPropEditor {
            get {
                return ResourceManager.GetString("ErrShowPropEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not get simulation parameter. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSimParam {
            get {
                return ResourceManager.GetString("ErrSimParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not suspend the simulation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSuspendSim {
            get {
                return ResourceManager.GetString("ErrSuspendSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not update {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrUpdate {
            get {
                return ResourceManager.GetString("ErrUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not set the policy of logger. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrUpdateLogPol {
            get {
                return ResourceManager.GetString("ErrUpdateLogPol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are any process and any stepper that do not exist in DM directory. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarnLoadDM {
            get {
                return ResourceManager.GetString("WarnLoadDM", resourceCulture);
            }
        }
    }
}
