//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.1433
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecell.IDE.Plugins.StaticDebugWindow {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ecell.IDE.Plugins.StaticDebugWindow.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   The number of brackets is not correct. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrBrackets {
            get {
                return ResourceManager.GetString("ErrBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get exception while system check the property of variable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrCheckVar {
            get {
                return ResourceManager.GetString("ErrCheckVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This Id include any invalid characters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrInvalidID {
            get {
                return ResourceManager.GetString("ErrInvalidID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This min value is largger than max value. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrMaxMin {
            get {
                return ResourceManager.GetString("ErrMaxMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This object do not connect any object. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNoConnect {
            get {
                return ResourceManager.GetString("ErrNoConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This property is not set the value. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNoSet {
            get {
                return ResourceManager.GetString("ErrNoSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t find this stepper. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNotExistStepper {
            get {
                return ResourceManager.GetString("ErrNotExistStepper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This process have the reference for variable that is not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNoVariable {
            get {
                return ResourceManager.GetString("ErrNoVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The value of this property should be the positive number. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrPositive {
            get {
                return ResourceManager.GetString("ErrPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The value of this property should be 0 or the positive number. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrPositiveZero {
            get {
                return ResourceManager.GetString("ErrPositiveZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Static &amp;Debugger... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemStaticDebugText {
            get {
                return ResourceManager.GetString("MenuItemStaticDebugText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Model Compliance に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ModelComplianceName {
            get {
                return ResourceManager.GetString("ModelComplianceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Network Compliance に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NetworkComplianceName {
            get {
                return ResourceManager.GetString("NetworkComplianceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t find error obejcts in this model. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoError {
            get {
                return ResourceManager.GetString("NoError", resourceCulture);
            }
        }
    }
}
