//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.3603
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecell.IDE.Plugins.StaticDebugWindow {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ecell.IDE.Plugins.StaticDebugWindow.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Unmatched parenthesis are found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrBrackets {
            get {
                return ResourceManager.GetString("ErrBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID string is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrInvalidID {
            get {
                return ResourceManager.GetString("ErrInvalidID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The minimum value is greater than the maximum value. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrMaxMin {
            get {
                return ResourceManager.GetString("ErrMaxMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Entity has no connection to any other Entity. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNoConnect {
            get {
                return ResourceManager.GetString("ErrNoConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The value of this property is not set. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNoSet {
            get {
                return ResourceManager.GetString("ErrNoSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This Stepper does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNotExistStepper {
            get {
                return ResourceManager.GetString("ErrNotExistStepper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This Process refers to the nonexistent Variable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNoVariable {
            get {
                return ResourceManager.GetString("ErrNoVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This property value should be a positive number. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrPositive {
            get {
                return ResourceManager.GetString("ErrPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The property value should be a positive number including zero. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrPositiveZero {
            get {
                return ResourceManager.GetString("ErrPositiveZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This Process has redundant Variable Reference which refer to the same Variable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSameVariable {
            get {
                return ResourceManager.GetString("ErrSameVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Auto static debugger に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemAutoDebug {
            get {
                return ResourceManager.GetString("MenuItemAutoDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execute static &amp;debugger に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemStaticDebugText {
            get {
                return ResourceManager.GetString("MenuItemStaticDebugText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Model consistency に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ModelComplianceName {
            get {
                return ResourceManager.GetString("ModelComplianceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Network consistency に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NetworkComplianceName {
            get {
                return ResourceManager.GetString("NetworkComplianceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are no Entities that violate consistencies. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoError {
            get {
                return ResourceManager.GetString("NoError", resourceCulture);
            }
        }
    }
}
